export const BOARD_DIMENSION = 11; //must be an odd number
export const HEXAGON_EDGE_LENGTH = window.screen.width/(BOARD_DIMENSION*6.0);
export const TOP_LEFT_HEXAGON_CENTER_X = 357 - (BOARD_DIMENSION - 2) * HEXAGON_EDGE_LENGTH;
export const TOP_LEFT_HEXAGON_CENTER_Y = HEXAGON_EDGE_LENGTH * 2.5;
export const HEXAGON_WIDTH = Math.sqrt(3)*HEXAGON_EDGE_LENGTH;
export const BOARD_WIDTH = HEXAGON_WIDTH * (BOARD_DIMENSION + 1.5) * 1.5;
export const BOARD_HEIGHT = HEXAGON_EDGE_LENGTH * (BOARD_DIMENSION + 1.5) * Math.sqrt(3);